prefix fuseki:  <http://jena.apache.org/fuseki#>
prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
prefix tdb:     <http://jena.hpl.hp.com/2008/tdb#>
prefix ja:      <http://jena.hpl.hp.com/2005/11/Assembler#>
prefix :        <#>

# TDB
# tdb:DatasetTDB  rdfs:subClassOf  ja:RDFDataset .
# tdb:GraphTDB    rdfs:subClassOf  ja:Model .
# <#aamaservice>  rdf:type fuseki:Service ;
#     fuseki:name              "aama" ;       # http://host:port/aama
#     fuseki:serviceQuery      "query" ;    # SPARQL query service
#     fuseki:serviceUpdate     "update" ;   # SPARQL update service
#     fuseki:serviceUpload     "upload" ;   # Non-SPARQL upload service
    # fuseki:serviceReadWriteGraphStore "data" ; # SPARQL RW Graph store
    # fuseki:serviceReadGraphStore      "get" ; # SPARQL R Graph store
    # fuseki:dataset           <#aamads> ;
# <#aamads> rdf:type      tdb:DatasetTDB ;
#     tdb:location "/var/TDB" ;
    # tdb:unionDefaultGraph true ;
SELECT DISTINCT ?s ?o ?p
WHERE {
      ?svc rdf:type fuseki:Service .
      ?svc ?o ?p .
}

