prefix rdf:	 <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:	 <http://www.w3.org/2000/01/rdf-schema#>
prefix aama:	 <http://id.oi.uchicago.edu/aama/2013/>
prefix aamas:	 <http://id.oi.uchicago.edu/aama/2013/schema/>
prefix arab:	 <http://id.oi.uchicago.edu/aama/2013/Arabic>

## Currently the <lang>.schema.rdf data contains statements like:
##     <http://id.oi.uchicago.edu/aama/2013/Afar> a aamas:Language .
##     <http://id.oi.uchicago.edu/aama/2013/Afar> rdfs:label "Afar" .


SELECT DISTINCT ?label ?lang
WHERE {
      ?lang rdf:type aamas:Language .
      ?lang rdfs:label ?label .
}
ORDER BY ASC(?label)

