prefix aama:	 <http://id.oi.uchicago.edu/aama/2013/>
prefix aamas:	 <http://id.oi.uchicago.edu/aama/2013/schema/>
prefix rdf:	 <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:	 <http://www.w3.org/2000/01/rdf-schema#>
prefix lang:	 <http://id.oi.uchicago.edu/aama/2013/Lang/>
SELECT DISTINCT ?reln
WHERE {
GRAPH <http://oi.uchicago.edu/aama/arbore> {
      ?reln aama:lang lang:Arbore .
#      ?prop rdfs:subPropertyOf <http://id.oi.uchicago.edu/aama/2013/muProperty> .
      ?prop rdfs:subPropertyOf rdf:Propery .
}}
ORDER BY ASC(?reln)

